spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v2/products/**
            - Path=/api/v2/categories/**
            - Path=/api/v2/images/**

        - id: ecommerce-service
          uri: lb://ECOMMERCE-SERVICE
          predicates:
            - Path=/api/v2/carts/**
            - Path=/api/v2/cartItems/**
