spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/akhil
    username: postgres  
    password: Eshwar@351
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off
