spring:
  cloud:
    gateway:
      routes:
        - id: PRODUCT-CATALOG-SERVICE
          uri: lb://PRODUCT-CATALOG-SERVICE
          predicates:
            - Path=/api/v2/products/**
            - Path=/api/v2/categories/**
            - Path=/api/v2/images/**

        - id: ECOMMERCE-SERVICE
          uri: lb://ECOMMERCE-SERVICE
          predicates:
            - Path=/api/v2/carts/**
            - Path=/api/v2/cartItems/**
